name: Typeorm UML
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 10.x
          - 12.x
          - 14.x
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci --ignore-scripts
        env:
          CI: true
      - name: Build project
        run: npm run build
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout typeorm-uml
        uses: actions/checkout@v2
      - name: Checkout typeorm/typescript-example
        uses: actions/checkout@v2
        with:
          repository: typeorm/typescript-example
          path: example
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install dependencies and build typeorm-uml
        run: |
          npm ci --ignore-scripts
          npm run build
        env:
          CI: true
      - name: Install dependencies and build typeorm/typescript-example
        working-directory: example
        run: |
          npm i
          npx tsc
      - name: Test uml diagram
        working-directory: example
        run: test "$(../bin/run)" = "$EXPECTED"
        env:
          EXPECTED: http://www.plantuml.com/plantuml/png/ZPDHQzim4CVVzIbk7GmR4h8Cyb9SqophjhwC4SBOmw38rjaMaIKZAIHUakzUINOJawLqDjZI_Ux-_vCbtnjBjTtKWf1t30ik4IpD14OeQOqZO9b_nu3ISjl2JPAbWIIJBFqZaq992uR_nRlfHyYLKFgkrBHDexukcVYCzEQitgonZNOnx0kEWXt12IQXyFOBrUjlIZ2KIyNIv8DBJ9D9O2dilE59fBWKwHJUpyFrJ-sfpWKsjRnM-V3LtwwoHiRfM6EkD1jAa8ep16DHex9jWwOBr6WhnVf9pdKka12h6h0ACcMjge5nfsQvaeIODPSDrRG6hJQIEG-96cQ3k71jUdbGsWaFWAaeKrikIoYeC3WW5PLigxcrA7isWBcWni2UWBi-qtnT1kE5NnLiAsunaBdMQji53T9I8ygkmdq4r1VWIDmAmnc11RLOAjsE8Ez740Crvvat3ZiEd45y2uy_Lj5q6eCBzti1_fnuz6k-N7oVBwDFivdZnvF7JsNi21htxBJ3w3zqtNaLLuG72RYpdgyUVg-6XjxWgLy1H_CoR4UladDZL-cvMP_oUDbmXrwoBx1hAopuS1YF3_jNFSZ9xAr4Se-I-V_z6G00
